name: todo_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  meta: ^1.15.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.4
  bloc: ^8.1.4
  sqflite: ^2.4.1
  flutter_slidable: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true
